/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restaurante.vista;


import java.awt.Graphics;

/**
 *
 * @author user
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form asdfg
     */
    public frmLogin() {
        initComponents();
        //h.drawRect(WIDTH, WIDTH, WIDTH, HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        panFondoEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panPrincipal.setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        lblUsuario.setText("Usuario");
        panPrincipal.add(lblUsuario);
        lblUsuario.setBounds(50, 100, 60, 30);

        lblContrasena.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        lblContrasena.setText("Contraseña");
        panPrincipal.add(lblContrasena);
        lblContrasena.setBounds(30, 150, 80, 30);

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/restaurante/imagenes/copas.png"))); // NOI18N
        panPrincipal.add(lblIcono);
        lblIcono.setBounds(140, 20, 70, 60);

        jButton1.setBackground(new java.awt.Color(36, 47, 86));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/restaurante/imagenes/doughnut.png"))); // NOI18N
        jButton1.setText("Loguearse");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/restaurante/imagenes/doughnutdos.png"))); // NOI18N
        panPrincipal.add(jButton1);
        jButton1.setBounds(110, 220, 130, 40);
        panPrincipal.add(jSeparator1);
        jSeparator1.setBounds(120, 130, 170, 20);
        panPrincipal.add(jSeparator2);
        jSeparator2.setBounds(120, 180, 170, 20);

        txtUsuario.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        txtUsuario.setText("Ingresa tu Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        panPrincipal.add(txtUsuario);
        txtUsuario.setBounds(120, 100, 170, 30);

        txtContrasena.setText("111111111111");
        txtContrasena.setBorder(null);
        txtContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContrasenaMouseClicked(evt);
            }
        });
        panPrincipal.add(txtContrasena);
        txtContrasena.setBounds(120, 150, 170, 30);

        getContentPane().add(panPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 330, 280));

        panFondoEncabezado.setBackground(new java.awt.Color(36, 47, 86));
        panFondoEncabezado.setForeground(new java.awt.Color(51, 51, 51));
        panFondoEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡Bienvenido!");
        panFondoEncabezado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 330, -1));

        getContentPane().add(panFondoEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        this.txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrasenaMouseClicked
        this.txtContrasena.setText("");
    }//GEN-LAST:event_txtContrasenaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panFondoEncabezado;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
